config/routes.rb
Anger::Application.routes.draw do
  root to: "projects#index"

  resources :projects do 
    resources :todo_lists
  end
  resources :todo_lists do
    resources :todos
  end
  
  resources :todos
  resources :todo_lists

  devise_for :users

  

end

app/models/project.rb
class Project < ActiveRecord::Base

	has_many :todo_lists

end

app/models/todo.rb
class Todo < ActiveRecord::Base
	belongs_to :todo_list
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
	belongs_to :project
	has_many :todos
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @todo_list = TodoList.new
    @todo_list.project_id = @project.id

  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :due_on)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
      @todo = Todo.new
      @todo.todo_list_id = @todo.id
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)
    @todo_list.project_id = params[:project_id]

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to project_path(@todo_list.project), notice: 'Todo list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todo_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    @todo.todo_list_id = params[:todo_list_id]

    respond_to do |format|    
      if @todo.save
        format.html { redirect_to todo_list_path(@todo.todo_list), notice: 'Todo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todo }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:todo_item)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
        <small>
                Powered by <a href="http://azadlabs.com" target="_blank">AzadLabs</a>
        </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top header-menu">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Anger App", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
       <ul class="nav">
                 <li class="activelink"><%= link_to "Projects", root_path %></li>
                 <li><%= link_to "About", root_path %></li>
       </ul> 
       <ul class="nav pull-right">
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
         <% end %>
       </ul>
                
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 
    <%= render 'layouts/header' %>

      <div class="container">
     
        <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
        <% end %>
     
        <%= yield %>

        <%= render 'layouts/footer' %>
      </div> 
 
 
</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project, html: { class: 'from-horizontal'}) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.input :name, autofocus: true %>
<%= f.input :description %>   
<%= f.input :due_on, order: [:month, :day, :year],:as => :date, :input_html => {:class => 'datepicker'} %>
 
     
  <div class="form-actions">
    <%= f.button :submit, class: 'btn' %>
  </div>
<% end %>

app/views/projects/_todo_list.html.erb
<div> 
  <p class="todolist"><%=  link_to todo_list.title , todo_list %></p>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
 <div id="all_project">
    <section class="projects cards">

      <div class="row">
         
        <div class="span2">
         <nav class="project_nav">
          <%= link_to 'New Project', new_project_path %>    
         </nav>
          
        </div>
        
        <div class="span10">
         <% @projects.each do |project| %>  
          
          <%= link_to project do %>
            <article class="card">
                
              <h5 class="project-name"><%= project.name %></h5>
              <p class="project-description"><%= truncate(project.description, length: 75) %></p>

              <p class="due-on">Due On  
                 <% if project.due_on %>
                  <%= "#{project.due_on.strftime("%B %d, %Y")}" %>  
                <% end %>
              </p>
              <p class="created-at">
                Created <%= "#{time_ago_in_words(project.created_at).gsub('about','')}  ago" %>               
              </p>

              
              <p class="updated-at">Last Updated  
                 
                  <%= "#{time_ago_in_words(project.updated_at.to_s).gsub('about','')}  ago" %>
                
              </p>

              
                <div class="people">
                  <%= image_tag('avatar.40.gif', class: 'avatar') %>
                </div>  
                
              </article>
            <% end %>
           <% end %>    
        </div>
      </div>
    </section>
  </div> 

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="main">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong> 
	  <%= @project.name %>
	  </strong>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= @project.description %>
	  <%= link_to ' Edit', edit_project_path(@project) %> |
	  <%= link_to 'Back', projects_path %>
	</p>
	<!-- start of todo list //-->
	<p>Add todolist</p>
	<%= render partial: 'todo_lists/form' %>
	
	<h3>TodoList</h3>

	<%= render partial: 'projects/todo_list', collection: @project.todo_lists %>
	<!-- end of todo list //-->
	
</div>

app/views/todo_lists/_form.html.erb
<%= simple_form_for([@project, @todo_list]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/todo_lists/_todo.html.erb
<div> 
  <p class="todolist"><%=  todo.todo_item %></p>
</div>

app/views/todo_lists/edit.html.erb
<h1>Editing todo_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<h1>Listing todo_lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.title %></td>
        <td><%= todo_list.description %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo list', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New todo_list</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<div class="main">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Title:</strong>
	  <%= @todo_list.title %>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= @todo_list.description %> 
	  <%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
	  <%= link_to 'Back', todo_lists_path %>
	</p>


		<!-- start of todo  //-->
		<p>Add todo</p>
		<%= render partial: 'todos/form' %>
		
		<h3>Todos</h3>

		<%= render partial: 'todo_lists/todo', collection: @todo_list.todos %>
	<!-- end of todo  //-->
</div>

app/views/todos/_form.html.erb
<%= simple_form_for([@todo_list, @todo]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :todo_item %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <thead>
    <tr>
      <th>Todo item</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.todo_item %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<div class="main">

	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Todo item:</strong>
	  <%= @todo.todo_item %>
	</p>

	<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>
</div>